#!/usr/bin/python
"""Usage:
    {0} <interface:port> <username:password> [realm]
"""

import os, sys
import logging
from twisted.internet import reactor
from jostedal.turn import TurnUdpServer


DEFAULTS = ['pexip.com']

logging.basicConfig(level=logging.DEBUG, format="%(levelname)s: %(message)s")

try:
    addr, credentials = sys.argv[1:3]
    interface, port = addr.split(':')
    username, password = credentials.split(':')
    options = sys.argv[3:] or DEFAULTS
    realm, = options
except:
    exit(__doc__.format(os.path.basename(__file__)))
else:
    server = TurnUdpServer(reactor, username, password, realm, port=int(port),
                           interface=interface)
    port = server.start()
    logging.info("Started %s on %s:%d", server, interface, port)
    reactor.run()
